title: "UCSD Computing & Data Sciences Undergraduate Conference"
description: "An opportunity for undergrads to publish and present research, projects, and ideas."

url: "https://jackdeterman.github.io"
baseurl: "/CDS_Conference"

# Use Minimal Mistakes
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "Submission"
    url: /submission/
  - title: "Schedule"
    url: /schedule/
  - title: "Contact"
    url: /contact/

# Sidebar
sidebar:
  - title: "Conference Info"
    children:
      - title: "Submission"
        url: /submission/
      - title: "Schedule"
        url: /schedule/
      - title: "FAQ"
        url: /faq/

# Theme settings
minimal_mistakes_skin: "sunrise"  # Options: default, air, dark, neon, etc.
