remote_theme: cotes2020/jekyll-theme-chirpy
plugins:
  - jekyll-include-cache
  
title: "UCSD Computing & Data Sciences Undergraduate Conference"
tagline: "An opportunity for undergrads to publish and present research, projects, and ideas."
description: "Official website for the UCSD Computing & Data Sciences Undergraduate Conference."

theme_mode: dark

nav:
  - title: "Home"
    url: /
  - title: "Submission"
    url: /submission/
  - title: "Schedule"
    url: /schedule/
  - title: "Contact"
    url: /contact/

sidebar:
  - title: "Conference Info"
    children:
      - title: "Submission"
        url: /submission/
      - title: "Schedule"
        url: /schedule/
      - title: "FAQ"
        url: /faq/

