remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
title: "UCSD Computing & Data Sciences Undergraduate Conference"
description: "An opportunity for undergrads to publish and present research, projects, and ideas."

show_repo_name: false
show_downloads: false

# Custom CSS
include: ["assets/css/custom.css"]
