title: "UCSD Computing & Data Sciences Undergraduate Conference"
description: "An opportunity for undergrads to publish and present research, projects, and ideas."

url: "https://jackdeterman.github.io"
baseurl: "/CDS_Conference"

# Use Minimal Mistakes
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache


author_profile:
  name: "Jack Determan"
  avatar: "/assets/img/jane.jpg"
  bio: "A passionate developer and writer exploring web technologies."
  location: "San Francisco, CA"
  email: "jane@example.com"
  website: "https://janedoe.com"
  social:
    twitter: janedoe
    github: janedoe
    linkedin: janedoe

header_pages:
- index.md
- submission.md
- schedule.md
- contact.md

atom_feed:
  hide: true

footer:
  links:
    - label: "Instagram"
      url: "https://www.instagram.com/sd_cyber_conf"
      icon: "fab fa-instagram"

# Theme settings
minimal_mistakes_skin: "sunrise"
include: ["assets/css/custom.css"]
